### ISSUE TITLE
MergeTool bug: StructRNA of type MergeTool has been removed

### ISSUE THREAD

**Issue by xan2622** [Stromberg90/Scripts#7]
I got this error inside blender-2.81-4764362ebb91-windows64.
```
Traceback (most recent call last):
  File "C:\Users\Nadine\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\MergeTool.py", line 87, in modal
    main(context, event, self.started)
  File "C:\Users\Nadine\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\MergeTool.py", line 61, in main
    bpy.ops.mesh.select_all(action='DESELECT')
  File "G:\Nadine\archived_softwares\blender\blender_dailybuild\2.81\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.mesh.select_all.poll() failed, context is incorrect

location: <unknown location>:-1
```

And this error, in the console:
```
.
.
.
Traceback (most recent call last):
  File "C:\Users\Nadine\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\MergeTool.py", line 35, in draw_callback_px
    if self.started:
  File "G:\Nadine\archived_softwares\blender\blender_dailybuild\2.81\scripts\modules\bpy_types.py", line 672, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type MergeTool has been removed
Traceback (most recent call last):
  File "C:\Users\Nadine\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\MergeTool.py", line 35, in draw_callback_px
    if self.started:
  File "G:\Nadine\archived_softwares\blender\blender_dailybuild\2.81\scripts\modules\bpy_types.py", line 672, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type MergeTool has been removed
Traceback (most recent call last):
  File "C:\Users\Nadine\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\MergeTool.py", line 35, in draw_callback_px
    if self.started:
  File "G:\Nadine\archived_softwares\blender\blender_dailybuild\2.81\scripts\modules\bpy_types.py", line 672, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type MergeTool has been removed
Traceback (most recent call last):
  File "C:\Users\Nadine\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\MergeTool.py", line 35, in draw_callback_px
    if self.started:
  File "G:\Nadine\archived_softwares\blender\blender_dailybuild\2.81\scripts\modules\bpy_types.py", line 672, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type MergeTool has been removed
.
.
.
```

**Comment by Stromberg90** [comment]
I belive this should be fixed in the latest update :)
